title: Ty Maxwell
description: Ty Maxwell is a musician, songwriter and writer currently based in the United States.
baseurl: ""
url: ""

# GitHub Pages settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md
  - .gitignore
